travis:
  secure:
    BINSTAR_TOKEN: X1l+bsJdyRV46edfLFcq1MQKTrdG1Mkdji3pPRBJMKYsopqMhT3zmN8oi3xB9yZ0M4n3nDtu63Q9myihZjSucmUCW1Xoh14qLlSvSSX5/GRc6kAvEme3/rDjXcgLMHvmMAEWgKVSjpljDp4V7W7ROH1uQyl5WRN/SZm/zg3mN1rlsuSJGAdpnDys2XZp5UrWpOqlTsNNLZ29q1LGZ+lrASvm14lkWrLfgcW5dXs+i7ptVOobFy4CJaOcT4Q2YgubR6RsdxKtUpVulTGi0W6ez6iwKL67D7pTRTSbTOOaVSkPx4UjI8ZR0f8nQXSc9nFPA5lWKOaXBCjGRlqTWMC/k2ceyCLZbANysPezrPVThp/XYof5crQjL097b9KodIQme0r/iubkszg1Y+KAhT5YElH3mAD+uxuVKzb4t5Y6xZf2a9Rrddqapem0J5SYqHFYL8860OAdWdKsPJK1nZXpQEHjCUFb2KvST7F1Gc2qb1HQUPOVxSyAwXGmtJSCwwy1eeq1MMhnnTzi9ttOZSzilKCn/5tYmkiFBw3vJm2Vk6SGPLHeGLrYpfM2DGUqbeItkjluplBOh3Zst/M+g7IxzljyNthnCA3TjOA4p1oErPp/IT836Dew7FVoLe6NIGRZRpWRjZJyOazxk17Lc8CLT+tVD0QJ+GYcXYFj3AgYXpk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
